# Generated by Django 4.1.10 on 2023-08-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_rename_email_port_mail_rename_message_port_mesage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='mesage',
            field=models.CharField(max_length=100),
        ),
    ]
